### ISSUE TITLE
OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by AlexYiLuo** [perslab/depict#27]
Hi, 

I tried to use DEPICT in two computers with the same error as below

Writing DEPICT loci
Traceback (most recent call last):
  File "src/python/depict.py", line 114, in <module>
    loci_log = write_depict_loci(analysis_path,label,association_pvalue_cutoff,collection_file,depict_gene_annotation_file,locus_file,mhc_start_bp,mhc_end_bp,plink_executable,genotype_data_plink_prefix,plink_clumping_distance, plink_clumping_r2,"%s_depict.tab"%label,number_random_runs,background_plink_clumping_pvalue,plink_clumping_snp_column_header,association_pvalue_cutoff_column_header,null_gwas_prefix,depict_contact_email,req_fraction_of_background_files,background_loci_dir_suffix,background_data_path)
  File "/home/yluo/SSc_PBC/DEPICT/src/python/depict_library.py", line 224, in write_depict_loci
    log_a_out, log_a_err = run_plink_clumping(plink_executable, genotype_data_plink_prefix, association_pvalue_cutoff, plink_clumping_distance, plink_clumping_r2, "{}/{}".format(analysis_path,plink_input_file), "{}/{}".format(analysis_path,label), plink_clumping_snp_column_header, plink_clumping_pvalue_column_header )
  File "/home/yluo/SSc_PBC/DEPICT/src/python/depict_library.py", line 131, in run_plink_clumping
    version = subprocess.Popen([plink_binary,"--version"],stdout=subprocess.PIPE).communicate()[0].split()
  File "/home/yluo/.conda/envs/depict/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/yluo/.conda/envs/depict/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

I used chmod to change the permission for depict.py, depict_library.py, subprocess.py, Plink and java, and also tried to use sudo to execute. But none of these work. I wonder where the problem might be?

Thank you very much!

YL

**Comment by AlexYiLuo** [comment]
Problem solved.

The "plink_executable: " should put the executable file. I put the directory.
